webtalk_init -webtalk_dir D:/OneDrive - Habib University/Semester 4/CA/Project/Pipelined Processor/Pipelined Processor.sim/sim_1/behav/xsim/xsim.dir/testbench_RISCV_Pipeline_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 29 12:10:14 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e30f7df-f747-4bef-907c-a3bba21ef6f6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b3ce33a0a8042c78aaa2f6e6522aeeb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3102919614 -regid "" -xml D:/OneDrive - Habib University/Semester 4/CA/Project/Pipelined Processor/Pipelined Processor.sim/sim_1/behav/xsim/xsim.dir/testbench_RISCV_Pipeline_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/OneDrive - Habib University/Semester 4/CA/Project/Pipelined Processor/Pipelined Processor.sim/sim_1/behav/xsim/xsim.dir/testbench_RISCV_Pipeline_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/OneDrive - Habib University/Semester 4/CA/Project/Pipelined Processor/Pipelined Processor.sim/sim_1/behav/xsim/xsim.dir/testbench_RISCV_Pipeline_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
